from _typeshed import Incomplete

import ast
from token_utils import _py_tokenize

class Token:
    end: Incomplete
    end_col: Incomplete
    end_row: Incomplete
    line: Incomplete
    start: Incomplete
    start_col: Incomplete
    start_row: Incomplete
    string: Incomplete
    type: Incomplete

    def __init__(self, token: Incomplete) -> None: ...
    def __eq__(self, other: Incomplete) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __contains__(self, str_arg: Incomplete) -> bool: ...
    def __len__(self) -> int: ...
    def clone(self) -> Incomplete: ...
    def indentation(self) -> Incomplete: ...
    def is_assignment(self) -> Incomplete: ...
    def is_bitwise(self) -> Incomplete: ...
    def is_open_bracket(self) -> Incomplete: ...
    def is_close_bracket(self) -> Incomplete: ...
    def is_bracket(self) -> Incomplete: ...
    def is_comment(self) -> Incomplete: ...
    def is_comparison(self) -> Incomplete: ...
    def is_complex(self) -> Incomplete: ...
    def is_f_string(self) -> Incomplete: ...
    def is_float(self) -> Incomplete: ...
    def is_identical(self, other: Incomplete) -> Incomplete: ...
    def is_identifier(self) -> Incomplete: ...
    def is_immediately_before(self, other: Incomplete) -> Incomplete: ...
    def is_immediately_after(self, other: Incomplete) -> Incomplete: ...
    def is_in(self, sequence_of_strings: Incomplete) -> Incomplete: ...
    def is_indentation(self) -> Incomplete: ...
    def is_integer(self) -> Incomplete: ...
    def is_keyword(self) -> Incomplete: ...
    def is_matching_bracket(self, other: Incomplete) -> Incomplete: ...
    def is_math_operator(self) -> Incomplete: ...
    def is_name(self) -> Incomplete: ...
    def is_newline(self) -> Incomplete: ...
    def is_number(self) -> Incomplete: ...
    def is_operator(self) -> Incomplete: ...
    def is_other_operator(self) -> Incomplete: ...
    def is_space(self) -> Incomplete: ...
    def is_string(self) -> Incomplete: ...
    def is_unclosed_string(self) -> Incomplete: ...

def add_operator(
    string: Incomplete, name: Incomplete, category: Incomplete = "other"
) -> Incomplete: ...
def make_fake_token(
    type: Incomplete = ...,
    string: Incomplete = "$",
    start: Incomplete = ...,
    end: Incomplete = ...,
    line: Incomplete = "",
) -> Incomplete: ...
