from typing import Final
from token_utils import _py_tokenize

class Token:
    end: tuple[int, int]
    end_col: int
    end_row: int
    line: str
    start: tuple[int, int]
    start_col: int
    start_row: int
    string: str
    type: int

    def __init__(
        self,
        token: (
            _py_tokenize.TokenInfo
            | tuple[int, str, tuple[int, int], tuple[int, int], str]
        ),
    ) -> None: ...
    def __eq__(self, other: Token | str) -> bool: ...  # type: ignore[override]
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __contains__(self, str_arg: str) -> bool: ...
    def __len__(self) -> int: ...
    def clone(self) -> Token: ...
    def indentation(self) -> int: ...
    def is_assignment(self) -> bool: ...
    def is_bitwise(self) -> bool: ...
    def is_open_bracket(self) -> bool: ...
    def is_close_bracket(self) -> bool: ...
    def is_bracket(self) -> bool: ...
    def is_comment(self) -> bool: ...
    def is_comparison(self) -> bool: ...
    def is_complex(self) -> bool: ...
    def is_f_string(self) -> bool: ...
    def is_float(self) -> bool: ...
    def is_identical(self, other: Token) -> bool: ...
    def is_identifier(self) -> bool: ...
    def is_immediately_before(self, other: Token) -> bool: ...
    def is_immediately_after(self, other: Token) -> bool: ...
    def is_in(self, sequence_of_strings: list[str]) -> bool: ...
    def is_indentation(self) -> bool: ...
    def is_integer(self) -> bool: ...
    def is_keyword(self) -> bool: ...
    def is_matching_bracket(self, other: Token) -> bool: ...
    def is_math_operator(self) -> bool: ...
    def is_name(self) -> bool: ...
    def is_newline(self) -> bool: ...
    def is_number(self) -> bool: ...
    def is_Null(self) -> bool: ...
    def is_operator(self) -> bool: ...
    def is_other_operator(self) -> bool: ...
    def is_space(self) -> bool: ...
    def is_string(self) -> bool: ...
    def is_unclosed_string(self) -> bool: ...

def add_operator(string: str, name: str, category: str = "other") -> bool: ...
def make_fake_token(
    type: int = ...,
    string: str = "$",
    start: tuple[int, int] = (0, 0),
    end: tuple[int, int] = (0, 0),
    line: str = "",
) -> Token: ...

NULL: Final[Token]
