from io import StringIO
import warnings
from token_utils import _py_tokenize
from token_utils.token_class import Token
from token_utils.custom_warnings import SemiColonWarning
from token_utils.utils import pairwise

from collections.abc import Iterator

def _fix_empty_line(source: str, prev_token: Token, last_token: Token) -> Token: ...
def generate_tokens(source: str) -> Iterator[Token]: ...
def tokenize(source: str) -> list[Token]: ...
def get_physical_lines(source: str) -> list[list[Token]]: ...
def get_logical_lines(source: str) -> list[list[Token]]: ...

__all__ = ["__all__"]
