from token_utils.token_class import Token
from collections.abc import Iterator, Iterable

class BracketStack:
    stack: list[Token]

    def __init__(self) -> None: ...
    def add(self, bracket: Token) -> Token | bool: ...
    def is_empty(self) -> bool: ...

class IndentStack:
    indent_keywords: list[str]
    same_indent_keywords: list[str]
    stack: list[Token]
    top_indent_keywords: list[str]

    def __init__(self) -> None: ...
    def add_top_indent_keyword(self, name: str) -> None: ...
    def add_same_indent_keyword(self, name: str) -> None: ...
    def print_stack(self) -> None: ...
    def top_item(self) -> Token: ...
    def update(self, line: list[Token]) -> Token: ...
    def is_token_in_named_block(self, token: Token, name: str) -> bool: ...

def split_at_token(
    seq: list[Token], token: Token
) -> tuple[list[Token], list[Token]]: ...
def pairwise(
    iterable: Iterable[Token], prev: int = 0
) -> Iterator[tuple[Token, Token]]: ...
def sliding_window(
    iterable: list[Token], n: int, prev: int = 0
) -> Iterator[tuple[Token, ...]]: ...
