from _typeshed import Incomplete

from collections import deque
from itertools import chain, islice
from token_utils.token_class import Token, make_fake_token

class BracketStack:
    stack: Incomplete

    def __init__(self) -> None: ...
    def add(self, bracket: Token) -> Token | bool: ...
    def is_empty(self) -> bool: ...

class IndentStack:
    indent_keywords: list[str]
    same_indent_keywords: list[str]
    stack: Incomplete
    top_indent_keywords: list[str]

    def __init__(self) -> None: ...
    def add_top_indent_keyword(self, name: str) -> Incomplete: ...
    def add_same_indent_keyword(self, name: str) -> Incomplete: ...
    def print_stack(self) -> None: ...
    def top_item(self) -> Incomplete: ...
    def update(self, line: Incomplete) -> Incomplete: ...
    def is_token_in_named_block(self, token: Token, name: str) -> Incomplete: ...

def split_at_token(seq: list[Token], token: Token) -> Incomplete: ...
def pairwise(iterable: list[Token], prev: int = 0) -> Incomplete: ...
def sliding_window(iterable: list[Token], n: int, prev: int = 0) -> Incomplete: ...
